server:
  port: 8086

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/flux_organization
    username: postgres
    password: erferferf

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
